####################################### Services
services:
  service-portainer:
    image: ahmettoguz/portainer-ce:2.29.0-alpine
    container_name: orchestration-portainer-c
    command: --admin-password-file /tmp/portainer_password
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - volume-portainer:/data
      - ./portainer_password:/tmp/portainer_password
    networks:
      - network-orchestration
    restart: ${RESTART_POLICY}
    # ports:
    #   - 9000:9000

####################################### Networks
networks:
  network-orchestration:
    external: true

####################################### Volumes
volumes:
  volume-portainer:
    name: volume-portainer
